<?php

// Plugin definition
$plugin = array(
  'title' => t('ecommerce product'),
  'category' => t('ecommerce'),
  'icon' => 'ecommerce_product.png',
  'theme' => 'ecommerce_product',
  'css' => 'ecommerce_product.css',

  'regions' => array(
    'wide' => t('Wide'),
    'left' => t('Left side'),
    'right' => t('Right side'),
    'wide_second' => t('Wide second'),
    'wide_third' => t('Wide third'),
    'wide_fourth' => t('Wide fourth')
  ),
);
